import type { ClothingItem, MatchingResponse, OccasionResponse, ScoredOutfit, ShoppingSuggestion } from '../types/wardrobe';
import { inferWardrobeSlot } from '../lib/wardrobeSlots';

export const MAX_RECOMMENDATIONS = 9;

function toNumber(value: unknown, fallback = 0): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return fallback;
}

function clampScore(value: unknown): number {
  const score = toNumber(value, 0);
  return Math.max(0, Math.min(100, Math.round(score)));
}

function safeText(value: unknown, fallback: string): string {
  if (typeof value !== 'string') return fallback;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function optionalText(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function parseObject(value: unknown): Record<string, unknown> {
  if (value && typeof value === 'object') {
    return value as Record<string, unknown>;
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {};
    } catch {
      return {};
    }
  }
  return {};
}

function normalizeItem(raw: unknown, fallbackId: string): Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> {
  const source = (raw ?? {}) as Record<string, unknown>;
  return {
    id: safeText(source.id, fallbackId),
    category: safeText(source.category, 'Unknown'),
    color: safeText(source.color, 'Unknown'),
    image_url: safeText(source.image_url, ''),
  };
}

function normalizeOptionalItem(raw: unknown, fallbackId: string): Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> | null {
  if (!raw || typeof raw !== 'object') return null;
  return normalizeItem(raw, fallbackId);
}

export function normalizeScoredOutfit(raw: unknown, fallbackRank: number): ScoredOutfit {
  const source = (raw ?? {}) as Record<string, unknown>;
  const breakdown = (source.breakdown ?? {}) as Record<string, unknown>;

  return {
    rank: toNumber(source.rank, fallbackRank),
    score: clampScore(source.score),
    breakdown: {
      color: clampScore(breakdown.color),
      style: clampScore(breakdown.style),
      occasion: clampScore(breakdown.occasion),
    },
    ai_reason: safeText(source.ai_reason ?? source.reason, 'Recommendation generated by backend.'),
    ai_tip: safeText(source.ai_tip ?? source.tip, 'Try a complementary accessory to complete this look.'),
    top: normalizeOptionalItem(source.top, `top-${fallbackRank}`),
    bottom: normalizeOptionalItem(source.bottom, `bottom-${fallbackRank}`),
    other: source.other
      ? normalizeItem(source.other, `other-${fallbackRank}`)
      : null,
  };
}

function inferScenarioFromLocks(lockedTopId?: string, lockedBottomId?: string, occasion?: string, lockedOtherId?: string): string {
  const hasTop = Boolean(lockedTopId);
  const hasBottom = Boolean(lockedBottomId);
  const hasOther = Boolean(lockedOtherId);
  const hasOccasion = Boolean(occasion);
  if (hasOther && hasOccasion) return 'locked_other+occasion';
  if (hasOther) return 'locked_other';
  if (hasTop && hasBottom && hasOccasion) return 'locked_top+locked_bottom+occasion';
  if (hasTop && hasBottom) return 'locked_top+locked_bottom';
  if (hasTop && hasOccasion) return 'locked_top+occasion';
  if (hasBottom && hasOccasion) return 'locked_bottom+occasion';
  if (hasTop) return 'locked_top';
  if (hasBottom) return 'locked_bottom';
  if (hasOccasion) return 'occasion';
  return 'default';
}

function mapCaseToScenario(caseValue: string, options?: { lockedTopId?: string; lockedBottomId?: string; occasion?: string }): string {
  const normalizedCase = caseValue.trim().toUpperCase();
  if (!['A', 'B', 'C', 'D', 'E'].includes(normalizedCase)) {
    return caseValue;
  }

  if (normalizedCase === 'A') {
    return options?.occasion ? 'occasion' : 'default';
  }
  if (normalizedCase === 'B') {
    return options?.occasion ? 'locked_top+occasion' : 'locked_top';
  }
  if (normalizedCase === 'C') {
    return options?.occasion ? 'locked_bottom+occasion' : 'locked_bottom';
  }
  if (normalizedCase === 'E') {
    return options?.occasion ? 'locked_other+occasion' : 'locked_other';
  }
  return options?.occasion ? 'locked_top+locked_bottom+occasion' : 'locked_top+locked_bottom';
}

export function normalizeMatchingResponse(
  payload: unknown,
  options?: {
    lockedTopId?: string;
    lockedBottomId?: string;
    lockedOtherId?: string;
    occasion?: string;
    lockedTopItem?: Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> | null;
    lockedBottomItem?: Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> | null;
  },
): MatchingResponse {
  const source = (payload ?? {}) as Record<string, unknown>;
  const rawOutfits = Array.isArray(source.outfits)
    ? source.outfits
    : Array.isArray(source.recommendations)
      ? source.recommendations
      : [];

  let outfits = rawOutfits
    .map((outfit, index) => normalizeScoredOutfit(outfit, index + 1))
    .sort((a, b) => b.score - a.score)
    .slice(0, MAX_RECOMMENDATIONS)
    .map((outfit, index) => ({ ...outfit, rank: index + 1 }));

  if (
    outfits.length === 0 &&
    source.selected_outfit_score &&
    options?.lockedTopItem &&
    options?.lockedBottomItem
  ) {
    const selected = source.selected_outfit_score as Record<string, unknown>;
    const selectedBreakdown = parseObject(selected.breakdown);
    outfits = [
      {
        rank: 1,
        score: clampScore(selected.score),
        breakdown: {
          color: clampScore(selectedBreakdown.color),
          style: clampScore(selectedBreakdown.style),
          occasion: clampScore(selectedBreakdown.occasion),
        },
        ai_reason: safeText(selected.reason, 'Selected outfit scored by backend.'),
        ai_tip: safeText(selected.tip, 'Try a complementary accessory to complete this look.'),
        top: options.lockedTopItem,
        bottom: options.lockedBottomItem,
        other: selected.other
          ? normalizeItem(selected.other, 'selected-other')
          : null,
      },
    ];
  }

  const rawScenario = safeText(source.scenario, '').trim();
  const rawCase = safeText(source.case, '').trim();
  const scenario = rawScenario.length > 0
    ? rawScenario
    : rawCase.length > 0
      ? mapCaseToScenario(rawCase, options)
      : inferScenarioFromLocks(options?.lockedTopId, options?.lockedBottomId, options?.occasion, options?.lockedOtherId);

  return {
    outfits,
    total_combinations_checked: toNumber(source.total_combinations_checked, outfits.length),
    scenario,
  };
}

function normalizeSuggestion(raw: unknown): ShoppingSuggestion {
  const source = (raw ?? {}) as Record<string, unknown>;
  const category = safeText(source.category, 'Topwear');
  const color = safeText(source.color, 'Neutral');
  const pattern = safeText(source.pattern, 'Solid');
  return {
    category,
    color,
    pattern,
    reason: safeText(source.reason, 'Suggested to improve recommendation coverage.'),
    search_query: safeText(source.search_query, `${color} ${pattern} ${category}`),
  };
}

export function normalizeOccasionResponse(
  recommendPayload: unknown,
  gapPayload: unknown,
  options?: {
    lockedTopItem?: Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> | null;
    lockedBottomItem?: Pick<ClothingItem, 'id' | 'category' | 'color' | 'image_url'> | null;
  },
): OccasionResponse {
  const source = (recommendPayload ?? {}) as Record<string, unknown>;
  const selectedScore = parseObject(source.selected_outfit_score);
  const selectedTop = parseObject(selectedScore.top);
  const selectedBottom = parseObject(selectedScore.bottom);
  const lockedTopItem = selectedTop.id
    ? {
        id: safeText(selectedTop.id, 'selected-top'),
        category: safeText(selectedTop.category, 'Topwear'),
        color: safeText(selectedTop.color, 'Unknown'),
        image_url: safeText(selectedTop.image_url, ''),
      }
    : options?.lockedTopItem ?? undefined;
  const lockedBottomItem = selectedBottom.id
    ? {
        id: safeText(selectedBottom.id, 'selected-bottom'),
        category: safeText(selectedBottom.category, 'Bottomwear'),
        color: safeText(selectedBottom.color, 'Unknown'),
        image_url: safeText(selectedBottom.image_url, ''),
      }
    : options?.lockedBottomItem ?? undefined;

  const matching = normalizeMatchingResponse(recommendPayload, {
    lockedTopItem,
    lockedBottomItem,
  });
  if (matching.outfits.length === 0) {
    throw new Error('No recommendation generated by backend.');
  }

  const suggestionsRaw = ((gapPayload ?? {}) as Record<string, unknown>).suggestions;
  const shoppingSuggestions = Array.isArray(suggestionsRaw)
    ? suggestionsRaw.map((item) => normalizeSuggestion(item))
    : [];

  const [recommended, ...alternatives] = matching.outfits;
  return {
    recommended_outfit: {
      ...recommended,
      rank: 1,
    },
    alternatives: alternatives.map((outfit, index) => ({ ...outfit, rank: index + 2 })),
    shopping_suggestions: shoppingSuggestions,
  };
}

export function normalizeWardrobeForRecommendation(rawItems: unknown[]): ClothingItem[] {
  return rawItems.map((item, index) => {
    const source = (item ?? {}) as Record<string, unknown>;
    const description = parseObject(source.description);
    const category = safeText(source.category ?? description.category ?? description.type, 'Unknown');
    const color = safeText(source.color ?? description.color, 'Unknown');
    return {
      id: safeText(source.id, `item-${index}`),
      user_id: optionalText(source.user_id),
      image_url: safeText(source.image_url, ''),
      category,
      color,
      pattern: optionalText(source.pattern ?? description.pattern),
      sleeve_type: optionalText(source.sleeve_type ?? description.sleeve_type),
      type: inferWardrobeSlot(source.type, description.type, category),
      created_at: safeText(source.created_at, new Date().toISOString()),
      updated_at: safeText(source.updated_at ?? source.created_at, new Date().toISOString()),
      occasion: optionalText(source.occasion ?? description.occasion) || null,
    } as ClothingItem;
  });
}
